create or replace TABLE gbi_fraud_bap_db.ai_live_biz_app.TRADER_TFA_SL_TH_LOGGING (
	RUN_TS TIMESTAMP_NTZ(9),
	ORDER_ID VARCHAR(16777216),
	WEB_ORDER_ID VARCHAR(16777216),
	HUNTING_PATTERN VARCHAR(255),
	QUERY_TYPE VARCHAR(10)
);