"""
Export Trader Hunting pattern DDLs into a single consolidated SQL file,
labeled and grouped by pattern type (TH vs GCT), suitable for committing to a repo.

Prints progress to stdout as each pattern is fetched and written.

Usage:
    python export_active_patterns.py
    python export_active_patterns.py --output patterns_active.sql
    python export_active_patterns.py --include-inactive
    python export_active_patterns.py --split-by-type   # writes patterns_TH.sql + patterns_GCT.sql
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd
from ai.snowflake.compat.connection import sf


PATTERNS_TABLE = "gbi_fraud_bap_db.ai_live_biz_app.TRADER_HUNTING_PATTERNS"
VIEW_SCHEMA = "gbi_fraud_bap_db.ai_live_biz_app"

TYPE_LABELS = {
    "TH": "Trader Hunting Patterns",
    "GCT": "Good Customer Patterns",
}


# ---------- Snowflake I/O ----------

def load_patterns(include_inactive: bool = False) -> pd.DataFrame:
    where = "" if include_inactive else "WHERE ACTIVITY = 'Active'"
    q = f"""
        SELECT DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, CREATED_BY,
               CREATED_TS, QUERY_TYPE, ACTIVITY
        FROM {PATTERNS_TABLE}
        {where}
        ORDER BY QUERY_TYPE, TABLE_NAME
    """
    df = sf.run_query(q)
    df.columns = [c.upper() for c in df.columns]
    df = df.drop_duplicates(subset=["TABLE_NAME"], keep="last").reset_index(drop=True)
    return df


def get_ddl(table_name: str) -> str | None:
    q = f"select get_ddl('view', '{VIEW_SCHEMA}.{table_name}') as query"
    try:
        df = sf.run_query(q)
        df.columns = [c.upper() for c in df.columns]
        return df["QUERY"].iloc[0]
    except Exception as e:
        print(f"    ! DDL fetch failed for {table_name}: {e}", file=sys.stderr)
        return None


# ---------- Formatting ----------

def extract_columns(ddl: str) -> list[str]:
    if not ddl:
        return []
    m = re.search(r"CREATE\s+OR\s+REPLACE\s+VIEW\s+[\w\.]+\s*\(([^)]+)\)", ddl, re.IGNORECASE)
    if not m:
        return []
    return [c.strip() for c in m.group(1).split(",") if c.strip()]


def banner(text: str, char: str = "=", width: int = 80) -> str:
    line = char * width
    return f"-- {line}\n-- {text}\n-- {line}\n"


def format_pattern_block(row: pd.Series, ddl: str) -> str:
    cols = extract_columns(ddl)
    cols_str = ", ".join(cols) if cols else "(could not parse)"
    header = (
        f"-- {'-' * 78}\n"
        f"-- Pattern:    {row['TABLE_NAME']}\n"
        f"-- Type:       {row['QUERY_TYPE']} ({TYPE_LABELS.get(row['QUERY_TYPE'], 'Unknown')})\n"
        f"-- Activity:   {row['ACTIVITY']}\n"
        f"-- Created by: {row['CREATED_BY']}\n"
        f"-- Created:    {row['CREATED_TS']}\n"
        f"-- Columns ({len(cols)}): {cols_str}\n"
        f"-- {'-' * 78}\n"
    )
    ddl_clean = ddl.strip().rstrip(";") + ";"
    return header + ddl_clean + "\n\n"


def build_toc(df: pd.DataFrame) -> str:
    lines = ["-- TABLE OF CONTENTS", "--"]
    for qtype, label in TYPE_LABELS.items():
        group = df[df["QUERY_TYPE"] == qtype]
        if group.empty:
            continue
        lines.append(f"-- [{qtype}] {label} ({len(group)})")
        for name in group["TABLE_NAME"].tolist():
            lines.append(f"--     - {name}")
        lines.append("--")
    return "\n".join(lines) + "\n\n"


def build_file_header(df: pd.DataFrame, include_inactive: bool) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    scope = "ALL patterns (active + inactive)" if include_inactive else "ACTIVE patterns only"
    counts = df["QUERY_TYPE"].value_counts().to_dict()
    counts_str = ", ".join(f"{k}={v}" for k, v in sorted(counts.items())) or "none"
    return (
        banner("TRADER HUNTING — CONSOLIDATED PATTERN DDL EXPORT")
        + f"-- Generated:  {now}\n"
        + f"-- Scope:      {scope}\n"
        + f"-- Total:      {len(df)}  ({counts_str})\n"
        + f"-- Source:     {PATTERNS_TABLE}\n"
        + "--\n"
        + "-- Auto-generated by export_active_patterns.py — do not edit by hand.\n"
        + "-- Re-run the script to refresh from Snowflake.\n"
        + "-- " + "=" * 78 + "\n\n"
    )


# ---------- Orchestration ----------

def write_consolidated(df: pd.DataFrame, out_path: Path, include_inactive: bool) -> tuple[int, int]:
    """Stream patterns to file with live progress output."""
    total = len(df)
    written = 0
    failed = 0

    print(f"\n→ Writing {total} patterns to {out_path}")
    print("─" * 70)

    with out_path.open("w", encoding="utf-8") as f:
        f.write(build_file_header(df, include_inactive))
        f.write(build_toc(df))

        for qtype, label in TYPE_LABELS.items():
            group = df[df["QUERY_TYPE"] == qtype]
            if group.empty:
                continue

            print(f"\n[{qtype}] {label}  ({len(group)} patterns)")
            f.write(banner(f"SECTION: {qtype} — {label}  ({len(group)} patterns)"))
            f.write("\n")

            for i, (_, row) in enumerate(group.iterrows(), 1):
                name = row["TABLE_NAME"]
                print(f"  [{i:>3}/{len(group)}] {name:<50} ", end="", flush=True)

                ddl = get_ddl(name)
                if not ddl:
                    f.write(f"-- !! Skipped {name} — DDL fetch failed\n\n")
                    failed += 1
                    print("FAILED")
                    continue

                block = format_pattern_block(row, ddl)
                f.write(block)
                f.flush()  # tailing the file shows progress too

                cols = extract_columns(ddl)
                written += 1
                print(f"✓ ({len(cols)} cols, {len(ddl):,} chars)")

    print("─" * 70)
    print(f"Done: {written} written, {failed} failed → {out_path}")
    return written, failed


def write_split(df: pd.DataFrame, out_dir: Path, include_inactive: bool) -> None:
    for qtype in TYPE_LABELS:
        group = df[df["QUERY_TYPE"] == qtype].reset_index(drop=True)
        if group.empty:
            print(f"[{qtype}] no patterns, skipping")
            continue
        out_path = out_dir / f"patterns_{qtype}.sql"
        write_consolidated(group, out_path, include_inactive)


# ---------- CLI ----------

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", "-o", default="patterns_active.sql",
                   help="Output file path (ignored with --split-by-type)")
    p.add_argument("--include-inactive", action="store_true",
                   help="Include inactive patterns (default: active only)")
    p.add_argument("--split-by-type", action="store_true",
                   help="Write one file per type: patterns_TH.sql, patterns_GCT.sql")
    args = p.parse_args()

    print("Loading patterns from Snowflake...")
    df = load_patterns(include_inactive=args.include_inactive)
    if df.empty:
        print("No patterns found. Exiting.")
        sys.exit(0)

    counts = df["QUERY_TYPE"].value_counts().to_dict()
    print(f"Loaded {len(df)} patterns: " + ", ".join(f"{k}={v}" for k, v in counts.items()))

    if args.split_by_type:
        out_dir = Path(args.output).parent if Path(args.output).parent != Path("") else Path(".")
        write_split(df, out_dir, args.include_inactive)
    else:
        write_consolidated(df, Path(args.output), args.include_inactive)


if __name__ == "__main__":
    main()

